using System.Diagnostics;

namespace QuotesApi.Shared.Infrastructure.Telemetry;

// Single shared ActivitySource for QuotesApi's custom spans (as opposed to the spans
// auto-generated by the ASP.NET Core / EF Core / HttpClient instrumentation packages).
// Program.cs registers this same name via .AddSource(QuotesTelemetry.SourceName), so any
// Activity started from this source — from a controller, a minimal API handler, or a
// background job — is exported to Application Insights.
public static class QuotesTelemetry
{
    public const string SourceName = "QuotesApi";

    public static readonly ActivitySource ActivitySource = new(SourceName);
}
